### ISSUE TITLE
README issue - repo name changed?

### ISSUE THREAD

**Issue by noahwsmith** [fcrepo-exts/fcrepo-aws-deployer#7]
The README says to clone down `git clone https://github.com/lyrasis/fcrepo-terraform` - that does not resolve for the public. Was that repo renamed to this location?

**Comment by dbernstein** [comment]
Resolved by https://github.com/fcrepo-exts/fcrepo-aws-deployer/commit/c01ddb3e3a881aeda6210db316c1293237b41119
